services:
  app:
    build: .
    container_name: trybesmith
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trybesmith_db
      POSTGRES_HOST: db

  db:
    container_name: trybesmith_db
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trybesmith_db
networks:
  default:
    name: trybesmith_net
